In [38]:
# Customer Churn Prediction for a Telecom Company

# Phase 6 – Feature Engineering

# Objective
# The objective of this notebook is to create new features from the existing data that can improve the predictive performance of the machine learning model.

# Tasks
# - Load the cleaned dataset
# - Create new meaningful features
# - Validate the engineered features
# - Save the engineered dataset

In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_excel("../data/processed/cleaned_telco_customer_churn.xlsx")

In [41]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1

In [42]:
df["Tenure Group"] = pd.cut(
    df["Tenure Months"],
    bins=[0,12,24,48,72],
    labels=["0-12","13-24","25-48","49-72"]
)

In [43]:
df["Tenure Group"].value_counts()

Tenure Group
49-72    2239
0-12     2175
25-48    1594
13-24    1024
Name: count, dtype: int64

In [44]:
df["Monthly Charge Group"] = pd.qcut(
    df["Monthly Charges"],
    q=4,
    labels=["Low","Medium","High","Very High"]
)

In [45]:
df["Monthly Charge Group"].value_counts()

Monthly Charge Group
Medium       1766
Low          1762
Very High    1758
High         1757
Name: count, dtype: int64

In [46]:
service_columns = [
    "Phone Service",
    "Multiple Lines",
    "Online Security",
    "Online Backup",
    "Device Protection",
    "Tech Support",
    "Streaming TV",
    "Streaming Movies"
]

df["Total Services"] = (
    df[service_columns] == "Yes"
).sum(axis=1)

In [47]:
df["Total Services"].describe()

count    7043.000000
mean        3.362914
std         2.062031
min         0.000000
25%         1.000000
50%         3.000000
75%         5.000000
max         8.000000
Name: Total Services, dtype: float64

In [48]:
df["Senior Citizen"] = df["Senior Citizen"].map(
    {
        "Yes":1,
        "No":0
    }
)

In [49]:
df["Partner"] = df["Partner"].map(
    {
        "Yes":1,
        "No":0
    }
)

In [50]:
df["Dependents"] = df["Dependents"].map(
    {
        "Yes":1,
        "No":0
    }
)

In [51]:
df["Paperless Billing"] = df["Paperless Billing"].map(
    {
        "Yes":1,
        "No":0
    }
)

In [52]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce")
df["Tenure Months"] = pd.to_numeric(df["Tenure Months"], errors="coerce")

df["Average Monthly Spending"] = (
    df["Total Charges"] /
    df["Tenure Months"].replace(0, np.nan)
)

In [53]:
df["Customer Value"] = pd.qcut(
    df["Total Charges"],
    q=3,
    labels=["Low", "Medium", "High"]
)

In [54]:
contract_map = {
    "Month-to-month":1,
    "One year":12,
    "Two year":24
}

df["Contract Duration"] = df["Contract"].map(contract_map)

In [55]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Monthly Charges,Total Charges,Churn Label,Churn Value,Tenure Group,Monthly Charge Group,Total Services,Average Monthly Spending,Customer Value,Contract Duration
0,Male,0,0,0,2,Yes,No,DSL,Yes,Yes,...,53.85,108.15,Yes,1,0-12,Medium,3,54.075000,Low,1
1,Female,0,0,1,2,Yes,No,Fiber optic,No,No,...,70.70,151.65,Yes,1,0-12,High,1,75.825000,Low,1
2,Female,0,0,1,8,Yes,Yes,Fiber optic,No,No,...,99.65,820.50,Yes,1,0-12,Very High,5,102.562500,Medium,1
3,Female,0,1,1,28,Yes,Yes,Fiber optic,No,No,...,104.80,3046.05,Yes,1,25-48,Very High,6,108.787500,High,1
4,Male,0,0,1,49,Yes,Yes,Fiber optic,No,Yes,...,103.70,5036.30,Yes,1,49-72,Very High,6,102.781633,High,1

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Gender                    7043 non-null   str
 1   Senior Citizen            7043 non-null   int64
 2   Partner                   7043 non-null   int64
 3   Dependents                7043 non-null   int64
 4   Tenure Months             7043 non-null   int64
 5   Phone Service             7043 non-null   str
 6   Multiple Lines            7043 non-null   str
 7   Internet Service          7043 non-null   str
 8   Online Security           7043 non-null   str
 9   Online Backup             7043 non-null   str
 10  Device Protection         7043 non-null   str
 11  Tech Support              7043 non-null   str
 12  Streaming TV              7043 non-null   str
 13  Streaming Movies          7043 non-null   str
 14  Contract                  7043 non-null   str
 15  Paperless Billing         7043 non-null   int64
 16  Payment Method            7043 non-null   str
 17  Monthly Charges           7043 non-null   float64
 18  Total Charges             7032 non-null   float64
 19  Churn Label               7043 non-null   str
 20  Churn Value               7043 non-null   int64
 21  Tenure Group              7032 non-null   category
 22  Monthly Charge Group      7043 non-null   category
 23  Total Services            7043 non-null   int64
 24  Average Monthly Spending  7032 non-null   float64
 25  Customer Value            7032 non-null   category
 26  Contract Duration         7043 non-null   int64
dtypes: category(3), float64(3), int64(8), str(13)
memory usage: 1.9 MB

In [57]:
df.to_excel(
    "../data/processed/feature_engineered_telco_customer_churn.xlsx",
    index=False
)

In [58]:
# Observations

# The following new features were successfully created:

# - Tenure Group
# - Monthly Charge Group
# - Total Services
# - Average Monthly Spending
# - Customer Value
# - Contract Duration

# These engineered features are expected to improve the predictive capability of the machine learning models.